### ISSUE TITLE
Add some basic exmaples or docs~

### ISSUE THREAD

**Issue by PedroGao** [ccie18643/PyTCP#4]
I'm so happy to have this project to study, but all parts are coupled under one app.
I can't run ICMP or IP alone, all source code file is not easy to read and refactor, 
cound you consider adding some examples to run one protocol individually.

**Comment by ccie18643** [comment]
I am happy someone actually finds this project useful :) However, in TCP/IP stack you can't run protocols individually. They all depend on each other. You could technically decouple TCP and write emulator for running it without using any lower layer protocols but that really calls for separate project that would be purely oriented for simulating TCP mechanism in various network conditions (delay, packet loss, etc). I may actually consider working on it once i have some free time next year.
