### ISSUE TITLE
Don't reapond to rst with rst

### ISSUE THREAD

**Issue by shoham-b** [ccie18643/PyTCP#5]
Currently, if a packet is sent to a port which  is not in stack.sockets, then it is responded with rst.

The issue with such behaviour raises when a rst is received, instead of ignoring it, a rst is sent back (protocols/tcp/phrx.py:89).

This is especially problematic if you put two pytcp instances since they enter an infinite loop.

I'd love to fix that, just opening an issue to open it up for discussion.

**Comment by ccie18643** [comment]
Valid point. Something i definitely overlooked. Please feel free to fix. Just make sure you use the PyTCP_2_6 branch. Thank you.

**Comment by ccie18643** [comment]
This issue has been fixed in version 3.0.2. Closing.
