### ISSUE TITLE
Make it possible to import pytcp as a library

### ISSUE THREAD

**Issue by shoham-b** [ccie18643/PyTCP#6]
Currently, pytcp can be run as a script, using pytcp.py

It would have been nice to be able to import it as a library.

To do this a few things should be done -
- add setup.py\pyproject.toml file.
- either import relative or import including the root - pytcp.
- encapsulate stack.py in an exposed class.
- extract config.py to a configuration class, with the possibility of getting it from a file.

I'd love to do that, just opening an issue to open it up for discussion.

**Comment by ccie18643** [comment]
I was actually thinking about this for some time but never really got chance to get to it. Please feel free to work on it. Just make sure you use the PyTCP_2_6 branch. Thank you.

**Comment by ccie18643** [comment]
This is going to be implemented in 2.7.
